version: '3.8'
services:
  redis-server:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass password
    volumes:
      - cache:/data
  web-server:
    image: project94:1.0.0
    ports:
      - "8080:8080"
    links:
      - redis-server
volumes:
  cache:
    driver: local
